#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "kem.h"
#include "params.h"
#include "rng.h"

#define MAX_BATCH_TESTS 100
#define MAX_TOTAL_TESTS 10000
#define KAT_SEED_BYTES 48

static FILE *open_output(const char *dir, const char *name)
{
    char path[1024];
    int n = snprintf(path, sizeof(path), "%s/%s", dir, name);
    if (n < 0 || (size_t)n >= sizeof(path)) {
        fprintf(stderr, "Path too long for %s/%s\n", dir, name);
        exit(2);
    }

    FILE *fp = fopen(path, "w");
    if (fp == NULL) {
        fprintf(stderr, "Cannot open %s: %s\n", path, strerror(errno));
        exit(2);
    }
    return fp;
}

static void write_hex_bytes(FILE *fp, const uint8_t *buf, size_t len)
{
    for (size_t i = 0; i < len; i++) {
        fprintf(fp, "%02x\n", buf[i]);
    }
}

static void write_rsp_hex_line(FILE *fp, const char *name, const uint8_t *buf, size_t len)
{
    fprintf(fp, "%s = ", name);
    for (size_t i = 0; i < len; i++) {
        fprintf(fp, "%02X", buf[i]);
    }
    fprintf(fp, "\n");
}

int main(int argc, char **argv)
{
    const char *out_dir;
    int num_tests = 100;
    int start_test = 0;

    if (argc < 2 || argc > 4) {
        fprintf(stderr, "usage: %s <out_dir> [num_tests] [start_test]\n", argv[0]);
        return 2;
    }

    out_dir = argv[1];

    if (argc >= 3) {
        num_tests = atoi(argv[2]);
        if (num_tests <= 0 || num_tests > MAX_BATCH_TESTS) {
            fprintf(stderr, "num_tests must be in range 1..%d\n", MAX_BATCH_TESTS);
            return 2;
        }
    }
    if (argc >= 4) {
        start_test = atoi(argv[3]);
        if (start_test < 0 ||
            start_test > MAX_TOTAL_TESTS - num_tests) {
            fprintf(stderr,
                    "start_test range must fit within 0..%d\n",
                    MAX_TOTAL_TESTS - 1);
            return 2;
        }
    }

    FILE *kat_seed_fp = open_output(out_dir, "kat_seed48.hex");
    FILE *keygen_seed_fp = open_output(out_dir, "keygen_seed.hex");
    FILE *enc_seed_fp = open_output(out_dir, "enc_seed.hex");
    FILE *pk_fp = open_output(out_dir, "pk.hex");
    FILE *sk_fp = open_output(out_dir, "sk.hex");
    FILE *ct_fp = open_output(out_dir, "ct.hex");
    FILE *ss_enc_fp = open_output(out_dir, "ss_enc.hex");
    FILE *ss_dec_valid_fp = open_output(out_dir, "ss_dec_valid.hex");
    FILE *ct_invalid_fp = open_output(out_dir, "ct_invalid.hex");
    FILE *ss_dec_invalid_fp = open_output(out_dir, "ss_dec_invalid.hex");
    FILE *manifest_fp = open_output(out_dir, "manifest.txt");
    FILE *rsp_fp = open_output(out_dir, "kat_rsp_with_invalid.txt");

    uint8_t entropy_input[KAT_SEED_BYTES];
    uint8_t kat_seeds[MAX_BATCH_TESTS][KAT_SEED_BYTES];
    uint8_t generated_seed[KAT_SEED_BYTES];
    uint8_t keygen_seed[2 * KYBER_SYMBYTES];
    uint8_t enc_coins[KYBER_SYMBYTES];
    uint8_t enc_seed[2 * KYBER_SYMBYTES];
    uint8_t pk[CRYPTO_PUBLICKEYBYTES];
    uint8_t sk[CRYPTO_SECRETKEYBYTES];
    uint8_t ct[CRYPTO_CIPHERTEXTBYTES];
    uint8_t ct_invalid[CRYPTO_CIPHERTEXTBYTES];
    uint8_t ss_enc[CRYPTO_BYTES];
    uint8_t ss_dec_valid[CRYPTO_BYTES];
    uint8_t ss_dec_invalid[CRYPTO_BYTES];

    for (int i = 0; i < KAT_SEED_BYTES; i++) {
        entropy_input[i] = (uint8_t)i;
    }

    /*
     * The NIST KAT flow first generates the complete request-seed sequence
     * from one DRBG instance. Each response is then generated by reseeding a
     * fresh DRBG with the corresponding request seed. Generate only the
     * selected batch into memory while advancing through the global sequence.
     */
    randombytes_init(entropy_input, NULL, 256);
    for (int test = 0; test < start_test + num_tests; test++) {
        if (randombytes(generated_seed, sizeof(generated_seed)) != 0) {
            fprintf(stderr, "KAT seed generation failed at test %d\n", test);
            return 1;
        }
        if (test >= start_test) {
            memcpy(kat_seeds[test - start_test],
                   generated_seed,
                   sizeof(generated_seed));
        }
    }

    fprintf(rsp_fp, "# %s\n\n", CRYPTO_ALGNAME);

    for (int local_test = 0; local_test < num_tests; local_test++) {
        int test = start_test + local_test;
        const uint8_t *kat_seed = kat_seeds[local_test];

        randombytes_init((unsigned char *)kat_seed, NULL, 256);

        if (randombytes(keygen_seed, sizeof(keygen_seed)) != 0) {
            fprintf(stderr, "Keygen seed generation failed at test %d\n", test);
            return 1;
        }

        if (crypto_kem_keypair_derand(pk, sk, keygen_seed) != 0) {
            fprintf(stderr, "crypto_kem_keypair_derand failed at test %d\n", test);
            return 1;
        }

        if (randombytes(enc_coins, sizeof(enc_coins)) != 0) {
            fprintf(stderr, "Encaps seed generation failed at test %d\n", test);
            return 1;
        }

        memset(enc_seed, 0, sizeof(enc_seed));
        memcpy(enc_seed, enc_coins, sizeof(enc_coins));

        if (crypto_kem_enc_derand(ct, ss_enc, pk, enc_coins) != 0) {
            fprintf(stderr, "crypto_kem_enc_derand failed at test %d\n", test);
            return 1;
        }

        if (crypto_kem_dec(ss_dec_valid, ct, sk) != 0) {
            fprintf(stderr, "crypto_kem_dec(valid) failed at test %d\n", test);
            return 1;
        }

        if (memcmp(ss_enc, ss_dec_valid, CRYPTO_BYTES) != 0) {
            fprintf(stderr, "C reference valid decaps mismatch at test %d\n", test);
            return 1;
        }

        memcpy(ct_invalid, ct, sizeof(ct_invalid));
        ct_invalid[test % CRYPTO_CIPHERTEXTBYTES] ^= (uint8_t)(1u << (test % 8));

        if (crypto_kem_dec(ss_dec_invalid, ct_invalid, sk) != 0) {
            fprintf(stderr, "crypto_kem_dec(invalid) failed at test %d\n", test);
            return 1;
        }

        write_hex_bytes(kat_seed_fp, kat_seed, KAT_SEED_BYTES);
        write_hex_bytes(keygen_seed_fp, keygen_seed, sizeof(keygen_seed));
        write_hex_bytes(enc_seed_fp, enc_seed, sizeof(enc_seed));
        write_hex_bytes(pk_fp, pk, sizeof(pk));
        write_hex_bytes(sk_fp, sk, sizeof(sk));
        write_hex_bytes(ct_fp, ct, sizeof(ct));
        write_hex_bytes(ss_enc_fp, ss_enc, sizeof(ss_enc));
        write_hex_bytes(ss_dec_valid_fp, ss_dec_valid, sizeof(ss_dec_valid));
        write_hex_bytes(ct_invalid_fp, ct_invalid, sizeof(ct_invalid));
        write_hex_bytes(ss_dec_invalid_fp, ss_dec_invalid, sizeof(ss_dec_invalid));

        fprintf(rsp_fp, "count = %d\n", test);
        write_rsp_hex_line(rsp_fp, "seed", kat_seed, KAT_SEED_BYTES);
        write_rsp_hex_line(rsp_fp, "keygen_seed", keygen_seed, sizeof(keygen_seed));
        write_rsp_hex_line(rsp_fp, "enc_seed", enc_seed, sizeof(enc_seed));
        write_rsp_hex_line(rsp_fp, "pk", pk, sizeof(pk));
        write_rsp_hex_line(rsp_fp, "sk", sk, sizeof(sk));
        write_rsp_hex_line(rsp_fp, "ct", ct, sizeof(ct));
        write_rsp_hex_line(rsp_fp, "ss", ss_enc, sizeof(ss_enc));
        write_rsp_hex_line(rsp_fp, "ct_invalid", ct_invalid, sizeof(ct_invalid));
        write_rsp_hex_line(rsp_fp, "ss_invalid", ss_dec_invalid, sizeof(ss_dec_invalid));
        fprintf(rsp_fp, "\n");
    }

    fprintf(manifest_fp, "algorithm=Kyber512\n");
    fprintf(manifest_fp, "source=nistkat_AES256_CTR_DRBG\n");
    fprintf(manifest_fp, "start_test=%d\n", start_test);
    fprintf(manifest_fp, "num_tests=%d\n", num_tests);
    fprintf(manifest_fp, "end_test=%d\n", start_test + num_tests - 1);
    fprintf(manifest_fp, "kat_seed_bytes=%d\n", KAT_SEED_BYTES);
    fprintf(manifest_fp, "keygen_seed_bytes=%llu\n", (unsigned long long)sizeof(keygen_seed));
    fprintf(manifest_fp, "enc_seed_bytes=%llu\n", (unsigned long long)sizeof(enc_seed));
    fprintf(manifest_fp, "pk_bytes=%d\n", CRYPTO_PUBLICKEYBYTES);
    fprintf(manifest_fp, "sk_bytes=%d\n", CRYPTO_SECRETKEYBYTES);
    fprintf(manifest_fp, "ct_bytes=%d\n", CRYPTO_CIPHERTEXTBYTES);
    fprintf(manifest_fp, "ss_bytes=%d\n", CRYPTO_BYTES);

    fclose(kat_seed_fp);
    fclose(keygen_seed_fp);
    fclose(enc_seed_fp);
    fclose(pk_fp);
    fclose(sk_fp);
    fclose(ct_fp);
    fclose(ss_enc_fp);
    fclose(ss_dec_valid_fp);
    fclose(ct_invalid_fp);
    fclose(ss_dec_invalid_fp);
    fclose(manifest_fp);
    fclose(rsp_fp);

    return 0;
}
