`timescale 1ns/1ps

// ZCU102 PL-only wrapper for the Kyber RISC-V SoC.
// Board clock: 125 MHz differential ref_clk_p/ref_clk_n.
// SoC clock:   100/125/150/166.667/180/190/200 MHz generated by MMCME4_BASE.
//
// Output mapping for quick demo:
//   gpio0_o[7:0] -> led[7:0]
// UART mapping:
//   uart_rx -> soc_top.uart_rx_i
//   uart_tx <- soc_top.uart_tx_o

module zcu102_soc_wrapper #(
    parameter integer SOC_CLOCK_PROFILE = 167,
    parameter integer BOOT_BYTES        = 16*1024,
    parameter integer BOOT_WRITABLE     = 0,
    parameter integer BOOTLOADER_ENABLE = 0,
    parameter integer BOOT_ROM_BYTES    = 16*1024,
    parameter integer SRAM_BYTES        = 16*1024,
    parameter integer KYBER_DATA_BYTES  = 8192,
    parameter         BOOT_INIT_FILE    = "",
    parameter         SRAM_INIT_FILE    = "",
    parameter [31:0]  RESET_VECTOR      = 32'h0000_0000
)(
    input  wire       ref_clk_p,
    input  wire       ref_clk_n,

    input  wire       cpu_reset,

    input  wire       uart_rx,
    output wire       uart_tx,

    input  wire [7:0] dip_sw,
    input  wire [4:0] pushbutton,

    inout  wire       i2c_scl,
    inout  wire       i2c_sda,

    output wire [7:0] led
);

    wire clk125_ibuf;
    wire clk125;

    localparam integer SOC_CLK_FREQ_HZ =
        (SOC_CLOCK_PROFILE == 100) ? 100_000_000 :
        (SOC_CLOCK_PROFILE == 125) ? 125_000_000 :
        (SOC_CLOCK_PROFILE == 150) ? 150_000_000 :
        (SOC_CLOCK_PROFILE == 180) ? 180_000_000 :
        (SOC_CLOCK_PROFILE == 190) ? 190_000_000 :
        (SOC_CLOCK_PROFILE == 200) ? 200_000_000 :
                                     166_666_667;
    localparam real MMCM_MULT_F =
        (SOC_CLOCK_PROFILE == 190) ? 9.500 :
        ((SOC_CLOCK_PROFILE == 150) || (SOC_CLOCK_PROFILE == 180)) ? 9.000 : 8.000;
    localparam real MMCM_CLKOUT_DIVIDE_F =
        (SOC_CLOCK_PROFILE == 100) ? 10.000 :
        (SOC_CLOCK_PROFILE == 125) ?  8.000 :
        (SOC_CLOCK_PROFILE == 150) ?  7.500 :
        (SOC_CLOCK_PROFILE == 180) ?  6.250 :
        (SOC_CLOCK_PROFILE == 190) ?  6.250 :
        (SOC_CLOCK_PROFILE == 200) ?  5.000 :
                                      6.000;

    wire clk_soc_mmcm;
    wire clk_soc;

    wire mmcm_fb;
    wire mmcm_fb_buf;
    wire mmcm_locked;

    wire [7:0] gpio0_o;
    wire       i2c_scl_i;
    wire       i2c_scl_o;
    wire       i2c_scl_oe;
    wire       i2c_sda_i;
    wire       i2c_sda_o;
    wire       i2c_sda_oe;
    wire [1:0] ext_irq_pulse;

    // ============================================================
    // ZCU102 differential PL clock input: 125 MHz
    // ============================================================
    IBUFDS #(
        .DIFF_TERM("FALSE"),
        .IBUF_LOW_PWR("FALSE")
    ) u_refclk_ibufds (
        .I  (ref_clk_p),
        .IB (ref_clk_n),
        .O  (clk125_ibuf)
    );

    BUFG u_clk125_bufg (
        .I(clk125_ibuf),
        .O(clk125)
    );

    // ============================================================
    // Supported profiles:
    // 100 MHz: VCO=1000 MHz, CLKOUT0 divide=10
    // 125 MHz: VCO=1000 MHz, CLKOUT0 divide=8
    // 150 MHz: VCO=1125 MHz, CLKOUT0 divide=7.5
    // 167 MHz: VCO=1000 MHz, CLKOUT0 divide=6 (166.667 MHz actual)
    // 180 MHz: VCO=1125 MHz, CLKOUT0 divide=6.25
    // 190 MHz: VCO=1187.5 MHz, CLKOUT0 divide=6.25
    // 200 MHz: VCO=1000 MHz, CLKOUT0 divide=5
    // ============================================================
    MMCME4_BASE #(
        .BANDWIDTH("OPTIMIZED"),
        .CLKIN1_PERIOD(8.000),

        .DIVCLK_DIVIDE(1),
        .CLKFBOUT_MULT_F(MMCM_MULT_F),
        .CLKFBOUT_PHASE(0.000),

        .CLKOUT0_DIVIDE_F(MMCM_CLKOUT_DIVIDE_F),
        .CLKOUT0_PHASE(0.000),
        .CLKOUT0_DUTY_CYCLE(0.500),

        .STARTUP_WAIT("FALSE")
    ) u_mmcm (
        .CLKIN1(clk125),
        .RST(cpu_reset),
        .PWRDWN(1'b0),

        .CLKFBOUT(mmcm_fb),
        .CLKFBOUTB(),
        .CLKFBIN(mmcm_fb_buf),

        .CLKOUT0(clk_soc_mmcm),
        .CLKOUT0B(),
        .CLKOUT1(),
        .CLKOUT1B(),
        .CLKOUT2(),
        .CLKOUT2B(),
        .CLKOUT3(),
        .CLKOUT3B(),
        .CLKOUT4(),
        .CLKOUT5(),
        .CLKOUT6(),

        .LOCKED(mmcm_locked)
    );

    BUFG u_mmcm_fb_bufg (
        .I(mmcm_fb),
        .O(mmcm_fb_buf)
    );

    BUFG u_clk_soc_bufg (
        .I(clk_soc_mmcm),
        .O(clk_soc)
    );

    // Keep SoC reset asserted until the generated clock is stable.
    wire soc_rst = cpu_reset | ~mmcm_locked;

    assign led = gpio0_o;

    zcu102_button_irq_filter u_ext0_button_irq (
        .clk_i(clk_soc),
        .rst_i(soc_rst),
        .button_i(pushbutton[0]),
        .irq_pulse_o(ext_irq_pulse[0])
    );

    zcu102_button_irq_filter u_ext1_button_irq (
        .clk_i(clk_soc),
        .rst_i(soc_rst),
        .button_i(pushbutton[1]),
        .irq_pulse_o(ext_irq_pulse[1])
    );

    // The I2C core drives only low. T=1 releases the PMOD line so the external
    // pull-up on the LCD backpack can produce a logic high.
    IOBUF u_i2c_scl_iobuf (
        .I(i2c_scl_o),
        .T(~i2c_scl_oe),
        .O(i2c_scl_i),
        .IO(i2c_scl)
    );

    IOBUF u_i2c_sda_iobuf (
        .I(i2c_sda_o),
        .T(~i2c_sda_oe),
        .O(i2c_sda_i),
        .IO(i2c_sda)
    );

    soc_top #(
        .CLK_FREQ_HZ(SOC_CLK_FREQ_HZ),
        .GPIO_WIDTH(8),
        .BOOT_BYTES(BOOT_BYTES),
        .BOOT_WRITABLE(BOOT_WRITABLE),
        .BOOTLOADER_ENABLE(BOOTLOADER_ENABLE),
        .BOOT_ROM_BYTES(BOOT_ROM_BYTES),
        .SRAM_BYTES(SRAM_BYTES),
        .KYBER_DATA_BYTES(KYBER_DATA_BYTES),
        .BOOT_INIT_FILE(BOOT_INIT_FILE),
        .SRAM_INIT_FILE(SRAM_INIT_FILE),
        .RESET_VECTOR(RESET_VECTOR)
    ) u_soc (
        .clk_i(clk_soc),
        .rst_i(soc_rst),

        .gpio0_i(8'h00),
        .gpio0_o(gpio0_o),
        .gpio0_oe(),

        .gpio1_i(dip_sw),
        .gpio1_o(),
        .gpio1_oe(),

        .i2c_scl_i(i2c_scl_i),
        .i2c_scl_o(i2c_scl_o),
        .i2c_scl_oe(i2c_scl_oe),
        .i2c_sda_i(i2c_sda_i),
        .i2c_sda_o(i2c_sda_o),
        .i2c_sda_oe(i2c_sda_oe),

        .uart_rx_i(uart_rx),
        .uart_tx_o(uart_tx),

        .ext_irq_i(ext_irq_pulse),
        .irq_o(),
        .irq_vector_o(),

        .cpu_trap_o(),
        .cpu_halted_o(),
        .cpu_fault_pc_o(),
        .cpu_fault_cause_o(),
        .cpu_pc_o()
    );

endmodule

module zcu102_button_irq_filter #(
    parameter integer DEBOUNCE_BITS = 21
)(
    input  wire clk_i,
    input  wire rst_i,
    input  wire button_i,
    output reg  irq_pulse_o
);
    reg sync_1;
    reg sync_2;
    reg stable;
    reg [DEBOUNCE_BITS-1:0] count;

    always @(posedge clk_i) begin
        if (rst_i) begin
            sync_1      <= 1'b0;
            sync_2      <= 1'b0;
            stable      <= 1'b0;
            count       <= {DEBOUNCE_BITS{1'b0}};
            irq_pulse_o <= 1'b0;
        end else begin
            sync_1      <= button_i;
            sync_2      <= sync_1;
            irq_pulse_o <= 1'b0;

            if (sync_2 == stable) begin
                count <= {DEBOUNCE_BITS{1'b0}};
            end else begin
                count <= count + {{(DEBOUNCE_BITS-1){1'b0}}, 1'b1};
                if (&count) begin
                    stable <= sync_2;
                    count  <= {DEBOUNCE_BITS{1'b0}};
                    if (sync_2)
                        irq_pulse_o <= 1'b1;
                end
            end
        end
    end
endmodule
